INSERT INTO interests (interest_id, interest_name) VALUES 
(2, 'Python'),
(3, 'Web Development'),
(4, 'Data Science'),
(5, 'Machine Learning'),
(6, 'Artificial Intelligence'),
(7, 'Cloud Computing'),
(8, 'Cybersecurity'),
(9, 'Blockchain Technology'),
(10, 'Mobile App Development'),
(11, 'Game Development'),
(12, 'DevOps'),
(13, 'Big Data'),
(14, 'Internet of Things (IoT)'),
(15, 'Augmented Reality'),
(16, 'Virtual Reality'),
(17, 'Quantum Computing'),
(18, 'Software Testing'),
(19, 'Database Management'),
(20, 'UI/UX Design'),
(21, 'Digital Marketing'),
(22, '3D Modeling and Animation');